#!/bin/bash

DEBNAME="lorascral"

systemctl enable $DEBNAME
systemctl daemon-reload

touch /var/log/lorascral.log
chown lorascralbot:lorascralbot /var/log/lorascral.log
chmod 644 /var/log/lorascral.log

chown -R lorascralbot:lorascralbot /usr/local/bin/$DEBNAME

if [ -f /tmp/$DEBNAME_service_runner ]; then
    service $DEBNAME start
    rm /tmp/$DEBNAME_service_runner
fi